### ISSUE TITLE
DPX slide template and wider story 

### ISSUE THREAD

**Issue by DPX-designer** [mozilla/dpx#3]
Following on the the crit on 10th September, we have an opportunity to carve our own identity and nope stick so rigidly to the styles prescribed in the Mozilla.design system. 

What is our story and the visual message we wish to convey?
What do we stand for? The mission.
The brand of the group

A strong, clear brand which elevates the content.
"Screams design and creativity"

### Slides to add to the template:
- A bleed image slide
- simple slides, i.e one large number or 3 words
- Contents page
- Acknowledgments page (at the beginning)
- Summary page (look at EOD example)

**Comment by mcroud** [comment]
**Feedback:**
- Brighter, not as intense. More upbeat.
- No need to stick with Mozilla style guides as long we have clear brand presence and adhere to logo usage.
- The visuals depicted here: https://mozilla.design/mozilla/visuals/ but not necessarily the illustrations.
