### ISSUE TITLE
v1 Team Collaboration Use Cases

### ISSUE THREAD

**Issue by mbransn** [mozilla/dpx#50]
Initial sketch and storyboard ideation for Hubs team collaboration product usages.

**Comment by mbransn** [comment]
@mcroud as you have sketches (or links) to share for review, please add them here and tag in @fernzharp + myself for review.

**Comment by mcroud** [comment]
@mbransn @fernzharp 
I'm compiling and adding all of my sketch work, imagery and thoughts to the following Figma file: https://www.figma.com/file/WPXrOoyrzlrDIy2EkMiSJn/Hubs-Meeting-App?node-id=0%3A1

**Comment by mbransn** [comment]
Thanks for sharing these through Matt! I've added some elements to the SC presentation to help visualize and highlight our next steps with this work. :) https://docs.google.com/presentation/d/1LmCWMpo1KCWH9OZPrtYoSqTwMwweNuvdYCi-Es2DlDc/edit#slide=id.ga36ebee221_2_1464

Will have a broader chat about this during 1:1 tomorrow, but for now I think you're on the right track visualizing the elements in the journey. Thank you!

**Comment by mbransn** [comment]
@mcroud I'm adding your [doc here ](https://docs.google.com/document/d/14lXuoEVBp2LxDSxUgiZkMo2mVec4Crm4g0p7HZDqoi0/edit?usp=sharing)and moving this issue to Review, thanks!

**Comment by mcroud** [comment]
Hi @mbransn, 
Sorry for the confusion! I thought the testing card was this one: https://app.zenhub.com/workspaces/dpx-hubs-5fb2cede17eb69001d393a6a/issues/mozilla/dpx-planning-and-intake/55  and I updated it with the doc link last week.
I've moved it to Review now.

**Comment by mcroud** [comment]
First concept test session will feature 4 concepts, 2 of collaboration and 2 of education. 
Currently awaiting review from research.
https://docs.google.com/document/d/14lXuoEVBp2LxDSxUgiZkMo2mVec4Crm4g0p7HZDqoi0/edit?usp=sharing
