### ISSUE TITLE
v1 Education Use Cases

### ISSUE THREAD

**Issue by mbransn** [mozilla/dpx#51]
Initial sketch and storyboard ideation for Hubs education product usages.

**Comment by mbransn** [comment]
@fernzharp as you have sketches (or links) to share for review, please add them here and tag in @mcroud + myself for review.

**Comment by fernzharp** [comment]
@mbransn & @mcroud Here is a link to the most recent storyboards for Hubs Language Exchange:
[https://www.figma.com/file/G60v2oaXm7PUIHQgelZvXx/Hubs-experience-journey?node-id=69%3A53](url)

I've added some placeholder text to tell the story and an alternate last panel that leaves out the "aha moment".

**Comment by fernzharp** [comment]
Thank you @mcroud.
1/3 Concepts  out for review: [https://docs.google.com/document/d/1Tz6AxfMK-uRpbzFWG9daIRNpi2bkYZ6bdnSbmy5yaY4/edit#heading=h.34z8e4gderx3](url)

**Comment by fernzharp** [comment]
Latest education concept here: [https://docs.google.com/document/d/1oPs2YRPFTVBx7LFxTTUjiERFsrBknQorp3WMvwCxvws/edit](url)
World wide Elementary for students.

**Comment by fernzharp** [comment]
Second education concept here: [https://docs.google.com/document/d/1HupJcmBhzuFhseX9S8ZxPj2klk3UugB9qXRunXCZBF0/edit](url)
Worldwide Elementary for teachers.
