### ISSUE TITLE
Refine experience journeys for education & team collaboration

### ISSUE THREAD

**Issue by mbransn** [mozilla/dpx#52]
Based on feedback from Hubs vision + experience strategy presentation, iterate experience journeys (and provisional personas) to focus on product use cases for education & team collaboration.

- [x] Create team collaboration journey focused on mtg product
- [x] Create educator journey for education focused product
- [x] Create student journey for education focused product
- [x] Update provisional personas to reflect product direction vs. platform direction
- [x] Share w/ @mcroud @fernzharp for further incorporation with use case ideation storyboards

**Comment by mbransn** [comment]
@mcroud @fernzharp product use cases with hypothesis, value proposition, provisional personas and journeys are in a [new Hubs Figma file here](https://www.figma.com/file/YC92369Qee2SWsikkNzbtV/Hubs-Product-Use-Cases?node-id=381%3A758). Note that I'm still updating journeys ahead of the 1 DEC steering committee meeting, but sharing this so you can review and feedback on the overall directions as you start to ideate as well. If you have additional use cases hypotheses please feel free to start populating them here in the same format.

**Comment by HeatherMcgeachy-ux** [comment]
Adding link to use case testing plan: [here](https://docs.google.com/document/d/1e7yPFthFgNjeQh0d6xRhIFt0xcotEY7-JDIbe9KeCWU/edit?usp=sharing)
