### ISSUE TITLE
Audience Test: v1 Education Use Cases

### ISSUE THREAD

**Issue by mbransn** [mozilla/dpx#56]
Utilizing [this template](https://docs.google.com/document/d/1e7yPFthFgNjeQh0d6xRhIFt0xcotEY7-JDIbe9KeCWU/edit), build 1-3 concept tests for feature flows of the Hubs Language Exchange and Hubs Elementary value propositions.

**Comment by fernzharp** [comment]
First concept test session will feature 4 concepts, 2 of collaboration and 2 of education.
Currently awaiting review from research.
https://docs.google.com/document/d/14lXuoEVBp2LxDSxUgiZkMo2mVec4Crm4g0p7HZDqoi0/edit?usp=sharing
