### ISSUE TITLE
Audience Test 3: v1 Team Collaboration Use Cases

### ISSUE THREAD

**Issue by mbransn** [mozilla/dpx#57]
Following up testing of team collaboration use cases based on v1 insights iteration.

**Comment by mbransn** [comment]
@mcroud I'm adding your [doc here ](https://docs.google.com/document/d/14lXuoEVBp2LxDSxUgiZkMo2mVec4Crm4g0p7HZDqoi0/edit?usp=sharing)and moving this issue to Review, thanks!

**Comment by mcroud** [comment]
Concept test 2 document is out for review: https://docs.google.com/document/d/1FK0SC5eH6XEPD5-EfMu8QvrW69KDC557Equ5Sh_mnNE/edit?usp=sharing
