### ISSUE TITLE
User Flows for VPN 2.1 PayPal (web)

### ISSUE THREAD

**Issue by nicolebjelica** [mozilla/dpx#70]
### Description

Design and UR Gantt chart:
[Design + UR VPN 2021 planning](https://docs.google.com/spreadsheets/d/1L-SuXwscu2f5fdprtQrWvkG2MI0E2J1Lhg1SJviazoc/edit?ts=5fd3b541#gid=1270933564)

PayPal to Subplat Timeline Engineering:
[PayPal integration to SubPlat timeline](https://docs.google.com/spreadsheets/d/1TDoDA0NxPPRxLNHqie970TLOF68Ty-Mvm8L7xrkQL_U/edit#gid=1270933564)

### Custom Fields
**STATUS**
At Risk

### Attachments
[SC update oct 2020](https://docs.google.com/presentation/d/13q0cMJAu829zaNhXmWn-taDaBdl2OG9KhQZazKPVJbo/edit#slide=id.g536bb85598_3_16)

### Comments from Trello
Heather McGeachy Nov 4 at 12:30 PM

We re-prioritized VPN cross-platform UX/UI improvements over FxA, IAP, and PayPal (this is reflected in slide 14 from S&P SC presentation from a week or so ago): [SC update oct 2020](https://docs.google.com/presentation/d/13q0cMJAu829zaNhXmWn-taDaBdl2OG9KhQZazKPVJbo/edit#slide=id.g536bb85598_3_16)

**Comment by nicolebjelica** [comment]
@malqinneh is there a way to add multiple labels to this issue? labels from trello: PXR, XD, VPN

**Comment by nicolebjelica** [comment]
@malqinneh is there an XD label? Same questions for Pocket (mobile, web, community)...I don't see it in the drop down label options

**Comment by malqinneh** [comment]
@nicolebjelica we removed the XD label since XD no longer exists. Pocket organizes their issues in Jira and so we don't have Pocket related tags in this repo.
