### ISSUE TITLE
User Flows for VPN 2.1 IAP (mobile)

### ISSUE THREAD

**Issue by nicolebjelica** [mozilla/dpx#72]
### STATUS
At Risk

### Attachments
[VPN SC update oct 2020](https://docs.google.com/presentation/d/13q0cMJAu829zaNhXmWn-taDaBdl2OG9KhQZazKPVJbo/edit#slide=id.g536bb85598_3_16)

### Activity from Trello
Gloria Kim Dec 2 at 12:49 PM
Jess Cook is replacing Mustafa for this

Heather McGeachy Nov 4 at 12:34 PM
We reprioritized VPN cross-platform UX/UI improvements over FxA, IAP, and PayPal (this is reflected in slide 14 from S&P SC presentation from a week or so ago)

**Comment by malqinneh** [comment]
Similar to the PayPal issue [here](https://github.com/mozilla/dpx-planning-and-intake/issues/70#event-4141415510) -- we completed this back in October and I'm not sure why it's coming back up here. Also, @jess-cook03 is the lead on VPN and she'll be able to share more info on this.

**Comment by jess-cook03** [comment]
This work has been completed and is documented in Figma (elsewhere) I am closing this issue.
