### ISSUE TITLE
Assess UX issues of hubs.mozilla.com and "Create a Room" task 

### ISSUE THREAD

**Issue by nicolebjelica** [mozilla/dpx#79]
### Description
Begin to periodically test hubs.mozilla.com and Create a Room task to assess UX issues, especially with first time users

### Status
done
### Checklists

- [x] **usability tests on hubs page & first time entry)**

**Comment by nicolebjelica** [comment]
Add Thomas to this issue
Add label: XD

**Comment by malqinneh** [comment]
Thomas needs to set up a GitHub account with two-factor authentication enabled in order to be tagged in issues here.

**Comment by HeatherMcgeachy-ux** [comment]
Need to add Dan & Matt to this issue (and zenhub?) @nicolebjelica

**Comment by HeatherMcgeachy-ux** [comment]
Several test plans exist and are ready to go to PXR review
Findings from Completed rounds: [Basic Understanding](https://docs.google.com/document/d/1XQjPD1-mAiahb0jjyrEbPKpT05Sl_0Ht8_0E1VtzRn4/edit?usp=sharing), [Basic understanding Refresh](https://docs.google.com/document/d/1BUc1aMHAkvMN6R3LRZDftQIw2kMxcdBtxHOhm5b_kzw/edit?usp=sharing)

**Comment by reganMoz** [comment]
The links you have above @HeatherMcgeachy-ux do not seem to apply to the title of this issue. Should we move them to a different  (their own) issue? this ideation and narrow down concepts may be complete?

**Comment by HeatherMcgeachy-ux** [comment]
@reganMoz I think we change the title of this issue..and move this one to complete? Refined info above.
