### ISSUE TITLE
VPN website design (flow, interaction design, architecture, test/iterations, maintenance)

### ISSUE THREAD

**Issue by nicolebjelica** [mozilla/dpx#96]
### Status

**Comment by malqinneh** [comment]
@jess-cook03 we had identified potential improvements to the VPN website last quarter with Wennie and the greater VPN team. We didn't go into detail about what exactly could be improved and how might we improve it. There's a lot to be done in that space that could benefit users having a strong narrative and comms helps understanding what Mozilla VPN is. This ticket was brought over from a DPX board in Trello which is now deprecated. Again, it was only brought in for documentation purposes, the S&P team will need to assess whether this is important to tackle given all other priorities.

**Comment by jess-cook03** [comment]
Thank you! Pulling this into documentation elsewhere. Closing issue.
